### PR TITLE
Change timezone to UTC

### LINKED ISSUE #1: Timezone ?
Should timezone be UTC instead of London ?

### PR DESCRIPTION
**Pull request by exussum12**
Matches servers and default settings for intl config

Fixes #1

### CODE REVIEW

**Comment by willitscale** [comment]
I was looking at this before, that zones directly doesn't exist

**Comment by exussum12** [comment]
My system it's a symlink to usr/share/zoneinfo/UCT does that exist in the container ? I am on phone atm but assumed it work work based on the VPS I was connected to

**Comment by willitscale** [comment]
Nope, I thought I could fix it this easily before, but while testing it I discovered it. Honestly, by default the container is UTC so it's easier just removing setting the timezone all together.

**Comment by exussum12** [comment]
That gives random PHP warnings though doesnt it ?

**Comment by willitscale** [comment]
I'll have a test and find out

**Comment by exussum12** [comment]
PHP error can be ignored by adding

[Date]
date.timezone = UTC


To the ini file

**Comment by willitscale** [comment]
Actually, your pull request is fine. It creates a symbol link and symbolic links don't need to reference something that exists. When PHP gets installed it also installs the zoneinfo which creates the zoneinfo and then the symbolic link is correct.

**Pull request merged**
